// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {NavBar} from "@/Components/Common/Nav/NavBar";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={``}
      >
        {/* <div className="w-full h-full bg-red-500">

        </div> */}
        <NavBar />
        {children}
      </body>
    </html>
  );
}
